baseURL: "https://ahmad-ilyas.netlify.app"
languageCode: "en-us"
title: "Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
#    - identifier: blog
#      name: Blog
#      title: Blog posts
#      url: /blogs
#      weight: 1
#    - identifier: gallery
#      name: Gallery
#      title: Blog posts
#      url: /gallery
#      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/ICON (2).png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ahmad Ilyas."
    subtitle: "and I am just a guy who likes to make stuff"
    content: "Passionate Electronics Engineering Sophomore | Robotics Enthusiast | Aeromodelling & Additive Manufacturing Aficionado"
    image: /images/pic (1).jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://resumeai.tiiny.site"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ahmad-ilyas-b79631278/
        - icon: fab fa-instagram
          url: https://www.instagram.com/_ahmad_ilyas_?igsh=MWhhMzZlY2M4bTd5aA==
        - icon: fab fa-github
          url: https://github.com/AhmadIlyas77
        - icon: fa fa-envelope
          url: ahmad7.ilyas@gmail.com

      

  # About
  about:
    enable: true
    title: "About Me"
    image: "/ICON (2).png"
    content: |-
      I'm Ahmad Ilyas, your friendly neighborhood tinkerer currently diving into the world of Electronics and Communication Engineering at Zakir Husain College of Engineering and Technology, Aligarh Muslim University. With a passion for making stuff that borders on obsession, I'm all about robotics, especially when it involves building RC planes that may or may not fly straight (but hey, it's the journey, right?). And let's not forget my addiction to 3D printing—there's just something about turning digital dreams into tangible objects! From soft actuators to analog electronics and embedded systems, I'm like a kid in a candy store, except the candy is technology, and I'm here to munch on it all. Whether I'm concocting new robots or attempting homemade chocolate chip cookies (because why not add a sprinkle of sweetness to engineering?), you can bet I'm always cooking up something exciting.

    skills:
      enable: true
      title: "Here are a few technical skills I have been developing recently:"
      items:
        - "Python and MicroPython"
        - "Computer Vision with OpenCV"
        - "C/C++"
        - "Scratch"
        - "CAD"
        - "Matlab and Simulink"
        - "LTSPICE"
        - "PCB Designing"
        - "3D-Printing Know-how"
        - "Graphics Design with Canva"
        - "Aeromodelling"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Core Team Member - Volunteer"
        company: "AMURoboclub"
        companyUrl: "https://www.amuroboclub.tech/"
        date: "May 2023 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: true
          content: I have been working as a core team member (Volunteer) since May 2023 at AMURoboclub.
        content: | 
          Have been involved in both managerial and technical aspects of various events, workshops, project and competion in the club:

          - Hosted and organised a workshop on the basics of Arduino and Motion of a Robotic Arm.
          - Invlolved in managment of various workshops, including OpenCV, CAD, PCB Design etc.
          - Involved in management, organization and hosting in AMURoboclub's techhnical fest - Vercera.
          - Made a 5-DOF Robotic arm with Bluetooth control via an Android App.
          - Made an RC-Plane to participate in IIT-Rorkee's technical fest.


      - job: "Central Team Member - Executive Member"
        company: "EDIC"
        companyUrl: "https://www.linkedin.com/in/engineering-design-and-implementation-club-amu-00b517251/"
        date: "Nov 2023 - present"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: true
          content: I have been working as an executive member at EDIC since November 2023.
        content: |
          As an executive member at EDIC, I have been involved in the organization and management of various workshops and events such as Analog design hackathon, Basics of LTSPICE etc.

          I have also participated in various workshops, training sessions and competitions organized by the club.     

      - job: "AMU's DD-Robocon Team 2023 - Team Member"
        company: "DD-Robocon Team 2023"
        date: "Sep 2022 - May 2023"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I was selected as part of AMU's DD-Robocon Team 2023, unnder the tutelage of AMURoboclub. Performed the following tasks:

          - 3D-Modellng and CAD of the robots.
          - PID speed conntrol of motors using rotary encoders.
          - Simulation of the robots using Matlab and Simulink.
          - Management of all the 3D-Printing.
          - Fabrication of the robots.

      - job: "Robotic Intern"
        company: "SPACE"
        companyUrl: "https://space.ind.in/roboticsinternship/"
        date: "July 2023 - Aug 2023"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          Learned about the history of robotics manipulators, different types of robotic manipulators and basics of programming for robots

      - job: "Intern"
        company: "ECE Dept"
        companyUrl: "https://www.amu.ac.in/department/electronics-engineering"
        date: "Dec 2023 - Jan 2024"
        content: |
          Learned how to simulate various amplifier stages using LTSPICE, including CS amplifier with passive load, and Emitter follower, and also learned about various types of active loads such as diode-connected load and current-source as a load. Also, developed direct commands for finding bandwidth and GBW.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor Of Technology (Electronics and Communication)"
        school:
          name: "Zakir Husain College of Engineering and Technology, AMU"
          url: "https://amu.ac.in/colleges/zakir-husain-college-of-engineering-and-technology"
        date: "2022 - present"
        GPA : "9.35 out of 10 (Currently)"
        
      - title: "Senior Secondary School (+2)"
        school:
          name: "Saiyyid Hamid Senior Secondary School, AMU"
          url: "https://www.amu.ac.in/schools/saiyyid-hamid-senior-secondary-school-boys/home-page"
        date: "2020-2022"
        GPA: "95.2%"
        content: |-
          PCM + Computer Science
          
       
      - title: "Secondary School (10th grade)"
        school:
          name: "St. Fidelis Sr. Sec. School"
          url: "https://stfidelisaligarh.org/"
        date: "2008-2020"
        GPA: "97.4%"
        
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: DD-Robocon
        content: The team for the same competition organised by AMURoboclub scored 100/100 in round 1 of DD-Robocn 2023.
        image: /images/achievment.jpg
      - title: Analog Design Hackathon Winner
        content: The competion was organised by EDIC. I designed a CS amplifer with 35db gain and 28uW power dissipation as per the problem statement.
        image: /images/achievment.jpg



  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: 5-DOF Robotic Arm
        content: A 5-DOF Robotic Arm which is controlled via Bluetooth using and Android app. It uses simplified forward kinematics and positions can be saved and repeated.
        image: /images/projects/RA.jpg
        badges:
          - "CAD"
          - "Arduino"
          - "Scratch"
          - "Forward Kinematics"
          - "C/C++"
          - "3D-Printing"

      - title: RC Plane for Flightfury
        content: A 1m wingspan, 7.2 WCL trainer plane with a drop mechanism, designed for IIT-R's technical fest - Cognizance and its aeromodelling competion Fligtfury. Coincidently, looks like FT-Tutor.
        image: /images/projects/RCP.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"

      - title: Programming-less Obstacle avoiding robot
        content: A simple beetle robot that avoids obstacle by reversing the direction of motor by using a common battery terminal and momentary SPDT switches.
        image: /images/projects/Beetlebot.jpg
        badges:
          - "Basic Circuits"

      - title: RC Hovercrafts
        content: A simple RC hovercraft built using PVC foamboard and 3D printed parts.
        image: /images/projects/hovercraft.jpg
        badges:
          - "CAD"
          - "3D-Printing"
          - "Power Systems"

      - title: DD Robocon
        content: Elephant and Rabbit Robots built for participation in DD-Robocon 2023.
        image: /images/projects/DDR.jpg
        badges:
          - "CAD"
          - "3D-Printing"
          - "Power Systems"
          - "Matlab and Simulink"
          - "PID speed control"
          - "PCB Design"
          - "Embedded systems"

      - title: CS Amplifier
        content: CS Amplifier designed for the Analog Design Hackathon, organised by EDIC (for specifications, see achievement section).
        image: /images/projects/CSA.jpg
        badges:
          - "LTSPICE"
      
      - title: Headphone Hanger
        content: 3D-printed magnetic headphone hanger.
        image: /images/projects/mhh.jpg
        badges:
          - "CAD"
          - "3D-Printing"

      - title: Pens Stand
        content: 3D-printed magnetic pen stand.
        image: /images/projects/mps1.jpg
        badges:
          - "CAD"
          - "3D-Printing"

      - title: 3-DOF Robotic Arm
        content: A 3-DOF Hyrdraulic Robootic Arm built with cardboard and medical syringes.
        image: /images/projects/Hydro.jpg

      - title: RC Plane 1
        content: My first ever RC Plane - FT-Flyer. Didn't fly great.
        image: /images/projects/ftf.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"

      - title: RC Plane 2
        content: My second ever RC Plane - Blu-Baby Primary Trainer. Fly decently.
        image: /images/projects/bb2.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"

      - title: RC Plane 3
        content: My third ever RC Plane - based on Blu-Baby Primary Trainer. Flew great.
        image: /images/projects/rcp1.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"

      - title: Another RC Plane 
        content: Another RC Plane I built - FT-Explorer.
        image: /images/projects/fte2.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"
         
      - title: RC Plane with Gyroscope
        content: Another Blu-Baby Trainer I built recently, this this time with a gyroscope so that my friends can learn how to fly.
        image: /images/projects/bbg.jpg
        badges:
          - "CAD"
          - "Aeromodelling"
          - "Power systems"


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: ahmad7.ilyas@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/AhmadIlyas77
      linkedin: https://www.linkedin.com/in/ahmad-ilyas-b79631278/
      instagram: https://www.instagram.com/_ahmad_ilyas_?igsh=MWhhMzZlY2M4bTd5aA==
      

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>